name: Test Docker

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  push:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run MSSQL container
      run: |
        docker run --network host -p 1433:1433 -d \
          -e "ACCEPT_EULA=Y" \
          -e "MSSQL_SA_PASSWORD=YourStrong@Passw0rd" \
          mcr.microsoft.com/mssql/server:latest
        sleep 10
        sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q "ALTER LOGIN [sa] WITH PASSWORD= '${{ secrets.SQLPASSWORD }}', CHECK_POLICY = OFF"

    - name: Build Server Docker Image
      run: |
        mv server/tomcat server/docker/tomcat
        docker build -t tomcat:majors_choice server/docker/tomcat

    - name: Run Server Docker Container
      run: |
        docker run --network host -d -p 8080:8080 \
          -e "PAYMENT_CODE=${{ secrets.PAYMENT_CODE }}" \
          -e "PAYMENT_SECRET=${{ secrets.PAYMENT_SECRET }}" \
          -e "SQLPASSWORD=${{ secrets.SQLPASSWORD }}" \
          -e "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" \
          -e "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" \
          -e "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          tomcat:majors_choice
