name: Test Docker

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  push:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build & Run Tomcat server
      run: |
        mv server/tomcat server/docker/tomcat
        docker build -t tomcat:majors_choice server/docker/tomcat