name: Run Docker Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker Hello World
      run: |
        docker run hello-world